#+TITLE: StarWar HomePage
* intro

  this is a game written in *CL* . It's very simple, but still better than the worm game for me. If you are curious about writting games on CL, and think the [[http://lispgames.org/index.php/Common_Worm][worm]] game /too/ simple, you may check this. 
  
  This game is developed under *sbcl* of linux, and I am not sure whether it could work under other platforms. 
  
* installation

  To run the game, you have to:
  
** install the latest *sbcl*
    
    If you are using Ubuntu or Debian, you can use aptitude to install this:
#+BEGIN_SRC shell
sudo apt-get install sbcl
#+END_SRC

    Or you may go to the [[www.sbcl.org][sbcl homepage]]. 

** install *quicklisp* on that sbcl 
   
   Quicklisp is commonly used in CL for installing packages. Refers to [[www.quicklisp.org/][it's homepage]] to get and make it work. 
   
** install required libraries
    
    here we need *lispbuilder-sdl* and *lispbuilder-sdl-ttf*. To install and load them, just run the codes below:
    
#+BEGIN_SRC lisp
(ql:quickload '("lispbuilder-sdl" "lispbuilder-sdl-ttf"))
#+END_SRC
 
    This will download, install, compile and load the required library. 

** configure /asdf/ system
    
    To let /asdf/ know my package, run this: 
#+BEGIN_SRC lisp
(push asdf:*central-registry* "PATH")
(push asdf:*central-registry* "PATH/lib")
#+END_SRC
    
    Here, *PATH* should be the path of /starwar/ directory. 

** load the game and run
    
    Finally, this will load and run the game:

#+BEGIN_SRC lisp
(require "org.xzpeter.game.starwar")
(org.xzpeter.game.starwar:run)
#+END_SRC

    have fun!

* how to play
  
  This will be filled in later on. 
